name: cpp-cmake-mingw-prebuilt-release-actions-workflow
on:
  push:
    paths-ignore:
      - 'README.md'
    # Sequence of patterns matched against refs/tags
    # tags:
    #   - '*' # Push events to matching v*, i.e. v1.0, v20.15.10

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
permissions:
    contents: write

jobs:
  build:
    # strategy:
    #   matrix:
    #     compiler:
    #     # - {
    #     #     name: "x86_64-8.1.0-release-posix-seh-rt_v6-rev0",
    #     #     url: "https://github.com/dirkarnez/cpp-tools/raw/main/x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z"
    #     #   }
    #     # - {
    #     #     name: "winlibs-x86_64-posix-seh-gcc-11.2.0-mingw-w64-9.0.0-r1",
    #     #     url: "https://github.com/brechtsanders/winlibs_mingw/releases/download/11.2.0-12.0.1-9.0.0-r1/winlibs-x86_64-posix-seh-gcc-11.2.0-mingw-w64-9.0.0-r1.zip"
    #     #   }
    #     # - {
    #     #   name: "13.1.0-202407240918mingw1310.7z",
    #     #   url: "https://download.qt.io/online/qtsdkrepository/windows_x86/desktop/tools_mingw1310/qt.tools.win64_mingw1310/13.1.0-202407240918mingw1310.7z"
    #     # }
    #     # - {
    #     #     name: "msvc2019"
    #     #   }

    runs-on: windows-latest
    env:
      libraryName: qtbase
      tagName: v6.10.0
    steps:
      # - uses: actions/checkout@v4
      #   with:
      #     repository: qt/qtbase
      #     ref: ${{ env.tagName }}
      #     path: ${{ env.libraryName }}
      #     submodules: true
      - uses: actions/checkout@v4
      
      - shell: cmd
        run: |
          .\setup.cmd
          
      - shell: cmd
        run: |
          .\download-qt.cmd

      - shell: cmd
        run: |
          .\local-build.cmd
          
      # - name: download compiler
      #   if: ${{  matrix.compiler.url }}
      #   shell: cmd
      #   run: |
      #     curl ${{ matrix.compiler.url }} -L --output compiler &&^
      #     7z.exe x compiler
      
      - shell: cmd
        run: |
          dir /S
          
      - shell: cmd
        run: |
          set DOWNLOADS_DIR=%USERPROFILE%\Downloads
          set DOWNLOADS_DIR_LINUX=%DOWNLOADS_DIR:\=/%
          set QT_VERSION=6.10.0
          set QT_VERSION_COARSE=6.10
          7z.exe a "${{ env.libraryName }}-${{ github.ref_name }}-13.1.0-202407240918mingw1310.zip" "%DOWNLOADS_DIR%\qtbase-everywhere-src-%QT_VERSION%\cmake-build\installation\*"
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.libraryName }}-${{ github.ref_name }}-13.1.0-202407240918mingw1310.zip"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
